version: "3.5"
services:
  mongodb:
    image: 'bitnami/mongodb:3.6'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"

  php:
    image: php:7.1-apache
    ports:
       - "80:80"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  
  tomcat:
     image: 'tomcat:9.0'
     ports:
        - "8080:8080"    