version: "3.5"

services:
   mongodb:
      image: 'bitnami/mongodb:3.6'
      networks:
         - backend
      labels:
         kompose.service.type: nodeport
      ports:
         - "27017:27017"
      volumes:
         - mongodb_data:/bitnami
      environment:
         - MONGODB_DATABASE=diaphen

   postgres:
      image: 'mdillon/postgis'
      networks:
         - backend
      restart: always
      ports:
         - "5432:5432"
      environment:
         - POSTGRES_PASSWORD=azerty
         - POSTGRES_USER=phis
         - POSTGRES_DB=diaphen
      volumes:
         - postgresql_data:/var/lib/postgresql/data

   php:
      build: ./apache
      networks:
         - backend
         - frontend
      ports:
         - "80:80"
      volumes:
         - web_data:/var/www/html
  
   tomcat:
      image: 'tomcat:9.0'
      networks:
         - backend      
      ports:
         - "8080:8080"
      volumes:
         - tomcat_conf:/usr/local/tomcat/conf/
         - tomcat_webapps:/usr/local/tomcat/webapps/
        
   adminer:
      image: adminer
      networks:
         - backend
         - frontend      
      restart: always
      ports:
         - 9090:8080
      
networks:
   frontend:
   backend:

volumes:
   postgresql_data:
   mongodb_data:
   web_data:
   tomcat_conf:
   tomcat_webapps: